CREATE TABLE
  IF NOT EXISTS wallets (
    user_id UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    balance NUMERIC(20, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW (),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW ()
  );